import {
	AlertTriangle,
	ArrowRight,
	ArrowUpRight,
	BookOpen,
	Check,
	ChevronLeft,
	ChevronRight,
	Copy,
	CreditCard,
	Dumbbell,
	File,
	FileText,
	HelpCircle,
	Home,
	Image,
	Laptop,
	LayoutPanelLeft,
	LineChart,
	Loader2,
	MessagesSquare,
	Moon,
	MoreVertical,
	NotebookPen,
	Package,
	Plus,
	Puzzle,
	Search,
	Settings,
	SunMedium,
	Trash,
	Trophy,
	User,
	X,
	type Icon as LucideIcon
	// type IconProps as LucideProps
} from 'lucide-svelte';
import GoogleIcon from '$lib/components/shared/icons/google-icon.svelte';
import GitHubIcon from '$lib/components/shared/icons/github-icon.svelte';
import TwitterIcon from '$lib/components/shared/icons/twitter-icon.svelte';
import AppleIcon from '$lib/components/shared/icons/apple-icon.svelte';

export type Icon = LucideIcon;

export const Icons = {
	add: Plus,
	apple: AppleIcon,
	arrowRight: ArrowRight,
	arrowUpRight: ArrowUpRight,
	billing: CreditCard,
	bookOpen: BookOpen,
	chevronLeft: ChevronLeft,
	chevronRight: ChevronRight,
	check: Check,
	close: X,
	copy: Copy,
	dashboard: LayoutPanelLeft,
	dumbbell: Dumbbell,
	ellipsis: MoreVertical,
	gitHub: GitHubIcon,
	google: GoogleIcon,
	help: HelpCircle,
	home: Home,
	laptop: Laptop,
	lineChart: LineChart,
	logo: Trophy,
	media: Image,
	messages: MessagesSquare,
	moon: Moon,
	notebookPen: NotebookPen,
	package: Package,
	page: File,
	post: FileText,
	puzzle: Puzzle,
	search: Search,
	settings: Settings,
	spinner: Loader2,
	sun: SunMedium,
	trash: Trash,
	twitter: TwitterIcon,
	user: User,
	warning: AlertTriangle
};
